openapi: 3.0.3
info:
  title: MCP API
  description: OpenAPI specification for the /mcp POST endpoint
  version: 1.0.0

paths:
  /mcp:
    post:
      summary: Submit MCP Data
      description: Accepts and processes data sent to the MCP endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "abc123"
                value:
                  type: string
                  example: "sample data"
      responses:
        '201':
          description: MCP data submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MCP data submitted successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
