openapi: 3.0.3
info:
  title: MCP API
  description: OpenAPI specification for the /mcp GET endpoint
  version: 1.0.0

paths:
  /mcp:
    get:
      summary: Get MCP Data
      description: Retrieves data from the MCP endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MCP data fetched successfully
        '500':
          description: Internal server error

